### ISSUE TITLE
HDMI输出4K只有30hz

### ISSUE THREAD

**Issue by midgod321** [YeeWee/DELL-3070MFF-EFI-OpenCore#4]
HDMI输出4K只有30hz,dp没试，要不再更新一波？macos13.1

**Comment by YeeWee** [comment]
dell这个电脑主要是bios把高分辨率开关屏蔽了，4k需要导出bios打开这个选项后再刷入。你可以上网找找相关教程

**Comment by midgod321** [comment]
CFG Lock DVMT说得是这两个东西吗，我电话给dell售后，说是hdmi是1.4协议的，所以只有30hz.我手头没有dp线，无法测试dp

**Comment by YeeWee** [comment]
> CFG Lock DVMT说得是这两个东西吗，我电话给dell售后，说是hdmi是1.4协议的，所以只有30hz.我手头没有dp线，无法测试dp

是的，2个东西。DVMT需要设置64MB or higher，dell的bios没有放出来，需要自己修改bios，设置好后再重新写入，这个很费劲，建议买根dp线测试线可能更容易些

**Comment by YeeWee** [comment]
> > CFG Lock DVMT说得是这两个东西吗，我电话给dell售后，说是hdmi是1.4协议的，所以只有30hz.我手头没有dp线，无法测试dp
> 
> 是的，2个东西。DVMT需要设置64MB or higher，dell的bios没有放出来，需要自己修改bios，设置好后再重新写入，这个很费劲，建议买根dp线测试线可能更容易些

刷新bios可参考
https://github.com/JimLee1996/Hackintosh_OptiPlex_9020#general-method-windows-recommanded

**Comment by midgod321** [comment]
我就是在这样搞得，设置了64m也解锁了cfg,不行，应该是这个hdmi接口只有1.4协议，输出不了4k30hz.dp好像输出不了，你这个efi

**Comment by midgod321** [comment]
试过了.dp可以4k60hz.hdmiz不行,不知道您的efi可否支持dp输出？

**Comment by YeeWee** [comment]
可以的，我用的就是dp

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: midgod321 ***@***.***>
发送时间: Monday, February 27, 2023 5:23:53 PM
收件人: YeeWee/DELL-3070MFF-EFI-OpenCore ***@***.***>
抄送: Mr.Huang ***@***.***>; Comment ***@***.***>
主题: Re: [YeeWee/DELL-3070MFF-EFI-OpenCore] HDMI输出4K只有30hz (Issue #4)


试过了.dp可以4k60hz.hdmiz不行,不知道您的efi可否支持dp输出？

―

**Comment by midgod321** [comment]
可否分享一下你的BIOS设置，非常需要。感谢

**Comment by YeeWee** [comment]
bios我是默认设置，除了刷新bios，更新了DVMT其他都是默认的。可能不同电脑bios不同，你需要从你的bios导出进行更新，这样才没有风险

刷新bios可参考
https://github.com/JimLee1996/Hackintosh_OptiPlex_9020#general-method-windows-recommanded

**Comment by YeeWee** [comment]
close
