### ISSUE TITLE
it is not working with Dell 3070 MMF for Ventura

### ISSUE THREAD

**Issue by sukarechhe** [YeeWee/DELL-3070MFF-EFI-OpenCore#5]
it is not working with Dell 3070 MMF for Ventura

**Comment by YeeWee** [comment]
you can use [Releases](https://github.com/YeeWee/DELL-3070MFF-EFI-OpenCore/releases) [v0.9.1](https://github.com/YeeWee/DELL-3070MFF-EFI-OpenCore/releases/tag/v0.9.1)

**Comment by sukarechhe** [comment]
Not working, same result. It is not able to boot when I use the given EFI. At the same time, I can boot from other EFI but they are not compatible with Mac Ventura

**Comment by sukarechhe** [comment]
@YeeWee - it stuck while booting at Apple logo and hang.
I have tried https://github.com/Diosim/dell-7520-hacOS - and working but it has network adapter issue.

**Comment by YeeWee** [comment]
you can try new releases v0.9.2

**Comment by sukarechhe** [comment]
Same result, getting stuck at the booting screen. any suggestion, please?

**Comment by sukarechhe** [comment]
Thanks for the quick response. I just extracted the given EFI in Pendrive and boot the computer first from USB and it just landed on the booting screen and got stuck on Apple logo. However, at the same time, I tried https://github.com/Diosim/dell-7520-hacOS and was able to boot it.

**Comment by YeeWee** [comment]
you can turn on the Verbose mode,and check where boot is stuck

1. Mount your EFI
2. Open your config.plist using any XML editor
3. To enable Verbose, add -v to boot-args key under the 7C436110-AB2A-4BBB-A880-FE41995C9F82 UUID list in the NVRAM section of your config.plist.. To disable Verbose, remove -v from boot-args key under the 7C436110-AB2A-4BBB-A880-FE41995C9F82 UUID list in the NVRAM section of your config.plist.
4. Save your config.plist
5. Restart your system.

NOTE: If the Verbose is not being enabled/disabled even after adding or removing -v from the Boot args, it is recommended to reset NVRAM twice at least for the full effect.

**Comment by sukarechhe** [comment]
Sure, thanks. let me give it a try and update you back. 
thanks again

**Comment by sukarechhe** [comment]
It stuck at "Unsupported PCH" in verbose mode.

**Comment by sukarechhe** [comment]
FYI, my processor is i5 9500 2.20 and HDD is M.2 Toshiba

**Comment by sukarechhe** [comment]
@YeeWee any hope, did you get a chance to look into it?

**Comment by YeeWee** [comment]
You can use Google to search for the error displayed on your screen. Your issue is likely encountered by many people, such as in this post: [Booting Opencore ends with "Unsupported PCH" and "gIOScreenlockstate"](https://www.insanelymac.com/forum/topic/347429-booting-opencore-ends-with-unsupported-pch-and-gioscreenlockstate/)

**Comment by YeeWee** [comment]
I also have i5 9500 2.20 and Toshiba M.2.

**Comment by sukarechhe** [comment]
@YeeWee seems strange working for you and not for me. anyways thanks.

**Comment by sukarechhe** [comment]
@YeeWee tried taking help from google, but nothing helped. can you please enlighten me on this?

**Comment by YeeWee** [comment]
could you post your stuck screen or text in verbose mode?

**Comment by sukarechhe** [comment]
https://wetransfer.com/downloads/0ac65ace8d24f28c93b4ce8ea61eee0420230609090313/7aae221de5970a4435006b8a6584d7c620230609090350/f99fc0?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid

**Comment by sukarechhe** [comment]
@YeeWee  I have recorded video and uploaded at above url
I have again installed fresh OS and tried 9.2 but it seems now rebooting. I tried verbose mode as your suggested.

**Comment by YeeWee** [comment]
Sorry, i couldn't identify any issues from the video and there is no place to figure out.
