### ISSUE TITLE
太惊喜了，还在更新

### ISSUE THREAD

**Issue by accbest** [YeeWee/DELL-3070MFF-EFI-OpenCore#6]
下面是我的配置简述，请问有无小白的教程可以告诉设置BIOS，导入U盘的啊，希望解惑，我现在是想安装黑苹果和win11双系统，不知怎么操作。
------------分割线----------------------

--------[ 概览 ]----------------------------------------------------------------------------------

  电脑型号            戴尔 OptiPlex 3070 台式电脑
  操作系统            Windows 10 64位 ( DirectX 12 )

  处理器              英特尔 Core i3-9100T @ 3.10GHz 四核
  主板                戴尔 02N3WF ( H370 芯片组 )
  主显卡              英特尔 UHD Graphics 630 ( 128 MB / 戴尔 )
  内存                8 GB ( 镁光 DDR4 2666MHz )
  主硬盘               BC511 NVMe SK hynix 256GB ( 256 GB / 固态硬盘 )
  显示器              SAC2700 HDMI ( 26.9 英寸  )
  声卡                瑞昱  @ 英特尔 High Definition Audio 控制器
  网卡                瑞昱 RTL8168/8111/8112 Gigabit Ethernet Controller / 戴尔

--------[ 主板 ]----------------------------------------------------------------------------------

  主板型号            戴尔 02N3WF
  芯片组              H370 芯片组
  序列号              /25F8143/CNPEC0004105BW/
  主板版本            A03
  BIOS版本            戴尔 Inc. 1.1.3  /  BIOS程序发布日期: 08/12/2019
  BIOS的大小          16384 KB

--------[ 处理器 ]--------------------------------------------------------------------------------

  处理器              英特尔 Core i3-9100T @ 3.10GHz 四核
  速度                3.10 GHz (100 MHz x 31.0)
  处理器数量          核心数: 4 / 线程数: 4
  插槽/插座           U3E1
  一级数据缓存        2 x 32 KB, 8-Way, 64 byte lines
  一级代码缓存        2 x 32 KB, 8-Way, 64 byte lines
  二级缓存            2 x 256 KB, 4-Way, 64 byte lines
  三级缓存            6 MB, 12-Way, 64 byte lines
  特征                MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, EM64T, EIST, Turbo Boost

**Comment by YeeWee** [comment]
b站上有很多详细安装教学视频，可以参考
